#!/bin/zsh
echo "brand:"
brand=''
read brand
echo "date(mmyy):"
date_mmy=''
read date_mmy
cp=1
# result=$(find /cygdrive/c/Users/mdevries/Pictures/$brand/cover/$date_mmy/ -type f ! -name '*.ini' 2> /dev/null)
result=$(find /Users/mdevries/Documents/$brand/cover/$date_mmy/ -type f ! -name '.DS_Store')

if [ $result ];then
  while read -r line;do
    echo "cover n°$cp: ${line##/*/}"
    (( cp=$cp+1 ))
  done <<<"$result"
else
  echo "$brand's cover of $date_mmy isn't available"
fi

echo "ouvrir le dossier ? Y | n"
resOpen=''
read resOpen
if [[ $resOpen = 'y' || $resOpen = 'Y' || $resOpen = 'Yes' || $resOpen = 'yes' || $resOpen = ''  ]];then
  # cygstart "/cygdrive/c/Users/mdevries/Pictures/$brand/cover/$date_mmy/"
  open "/Users/mdevries/Documents/$brand/cover/$date_mmy/"
else
  echo "your answer is \"$resOpen\"... ok guy, do what you have to do!"
fi
