#!/bin/zsh
usr=$USER
echo "mois:"
mois=''
read mois
echo "$mois/année:"
annee=''
read annee
echo "$mois/$annee"

# mkdir "C:\Users\$usr\Pictures\tl\cover\\$mois$annee"
mkdir "/Users/$usr/Documents/HO/cover/$mois$annee"
# cd "C:\Users\$usr\Pictures\tl\cover\\$mois$annee"
cd "/Users/$usr/Documents/HO/cover/$mois$annee"
# touch desktop.ini
# touch .DS_Store
# echo ".DS_Store: " >> .DS_Store
#
# -E disable backslash interpretation
  # echo -E "IconResource=C:\Users\$usr\Pictures\domoti\favicon\perso\months\\$mois.y$annee.ico,0" >> desktop.ini

cd ../
open "/Users/$usr/Documents/HO/cover/$mois$annee"

# + ouvrir R:/pdf
# open R:/
open /Volumes/PDFs\ Web/Idées\ Homme\ Web/CAID 
echo 'cp *01_Web* /cygdrive/c/Users/$usr/Pictures/ho/cover/0X17'
