#!/bin/zsh
usr=$USER
echo "mois:"
mois=''
read mois
echo "$mois/année:"
annee=''
read annee
echo "$mois/$annee"

# mkdir "C:\Users\$usr\Pictures\tl\cover\\$mois$annee"
mkdir "/Users/$usr/Documents/MM/cover/$mois$annee"
# cd "C:\Users\$usr\Pictures\tl\cover\\$mois$annee"
cd "/Users/$usr/Documents/MM/cover/$mois$annee"
# touch desktop.ini
touch .DS_Store
echo ".DS_Store: " >> .DS_Store
#
# -E disable backslash interpretation
  # echo -E "IconResource=C:\Users\$usr\Pictures\domoti\favicon\perso\months\\$mois.y$annee.ico,0" >> desktop.ini
  # attrib +s +h desktop.ini

cd ../
  # attrib +r $mois$annee
open "/Users/$usr/Documents/MM/cover/$mois$annee"

# + ouvrir R:/pdf
# open R:/
# cygstart R:/Temps\ L\ Web/CATL && cygstart R:/Ideal\ Pratique\ Web/CAIP
open /Volumes/PDFs\ Web/Marianne\ Mélodie\ Web/CAMM
echo 'cp *01_Web* /cygdrive/c/Users/$usr/Pictures/mm/cover/0X17'
