#!/bin/zsh
# ouverture planning (creaScript:2016)
# $1 == user input
var=$(pwd)
if [[ $1 == '18' ]]; then
  echo "ouverture du planning 20${1} -> /Volumes/service marketing $/WEB/Plan_WEB_20${1}.xls"
  # PC cygwin -> # cd K:/WEB/ && cygstart Plan_WEB_2017.xls
  cd /Volumes/service\ marketing\$/WEB/ && open Plan_WEB_2018.xls 
else
  echo "ouverture du planning 2019 -> /Volumes/service marketing $/WEB/Plan_WEB_2019.xls"
  # cd K:/WEB/ && cygstart Plan_WEB_2018.xls
  cd /Volumes/service\ marketing\$/WEB/ && open Plan_WEB_2019.xls
fi
cd $var